INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Panasonic', 800, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Sony', 700, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Apple', 1000, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Sony Notebook', 1000, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Hewlett Packard', 500, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Bianchi', 600, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Nike', 100, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Adidas', 200, NOW());
INSERT INTO public.PRODUCTS (ID_PRODUCT, NAME, PRICE, CREATED_AT) VALUES(RANDOM_UUID(),'Reebok', 300, NOW());
